# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.6.44

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./mvnw dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Check copyright
          command: ./tools/scripts/copyright.sh

      - run:
          name: Code checkstyle
          command: ./tools/scripts/checkstyle.sh

      - run:
          name: Build pandora
          command: ./mvnw clean compile

      - run:
          name: Unit tests
          command: ./mvnw test

      - run:
          name: Integration tests
          command: ./mvnw integration-test

      - run:
          name: Sonar Analysis
          command: ./mvnw verify -Pcoverage && ./tools/scripts/sonar-scanner.sh
